"""schema initial : groupes, deputes, scrutins, votes, analyses_ia, collectes_log, sources_meta

Revision ID: 5ad03a6d6c31
Revises: f5b43c4f8f69
Create Date: 2026-07-20 23:47:26.253924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad03a6d6c31'
down_revision: Union[str, Sequence[str], None] = 'f5b43c4f8f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collectes_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_run', sa.DateTime(), nullable=False),
    sa.Column('nb_scrutins_traites', sa.Integer(), nullable=False),
    sa.Column('nb_nouveaux', sa.Integer(), nullable=False),
    sa.Column('nb_analyses_generees', sa.Integer(), nullable=False),
    sa.Column('nb_erreurs', sa.Integer(), nullable=False),
    sa.Column('duree_s', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupes',
    sa.Column('id_an', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('nom_court', sa.String(length=50), nullable=False),
    sa.Column('couleur', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id_an')
    )
    op.create_table('scrutins',
    sa.Column('uid', sa.String(length=30), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('date_scrutin', sa.Date(), nullable=False),
    sa.Column('titre', sa.String(length=500), nullable=False),
    sa.Column('type_vote', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.String(length=50), nullable=False),
    sa.Column('nb_pour', sa.Integer(), nullable=False),
    sa.Column('nb_contre', sa.Integer(), nullable=False),
    sa.Column('nb_abstention', sa.Integer(), nullable=False),
    sa.Column('nb_non_votants', sa.Integer(), nullable=False),
    sa.Column('dossier_ref', sa.String(length=200), nullable=True),
    sa.Column('lien_an', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_scrutins_date_scrutin'), 'scrutins', ['date_scrutin'], unique=False)
    op.create_table('sources_meta',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('derniere_collecte', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('analyses_ia',
    sa.Column('scrutin_uid', sa.String(length=30), nullable=False),
    sa.Column('resume_factuel', sa.Text(), nullable=False),
    sa.Column('arguments_pour', sa.JSON(), nullable=False),
    sa.Column('arguments_contre', sa.JSON(), nullable=False),
    sa.Column('coherence_macro', sa.String(length=20), nullable=False),
    sa.Column('indicateurs_ref', sa.JSON(), nullable=False),
    sa.Column('modele_utilise', sa.String(length=50), nullable=False),
    sa.Column('tokens_utilises', sa.Integer(), nullable=False),
    sa.Column('genere_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrutin_uid'], ['scrutins.uid'], ),
    sa.PrimaryKeyConstraint('scrutin_uid')
    )
    op.create_table('deputes',
    sa.Column('id_an', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('groupe_id', sa.String(length=20), nullable=True),
    sa.Column('departement', sa.String(length=100), nullable=True),
    sa.Column('circonscription', sa.String(length=10), nullable=True),
    sa.Column('score_participation', sa.Float(), nullable=True),
    sa.Column('score_loyaute', sa.Float(), nullable=True),
    sa.Column('score_majorite', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['groupe_id'], ['groupes.id_an'], ),
    sa.PrimaryKeyConstraint('id_an')
    )
    op.create_index(op.f('ix_deputes_groupe_id'), 'deputes', ['groupe_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scrutin_uid', sa.String(length=30), nullable=False),
    sa.Column('depute_id', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.Column('par_delegation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['depute_id'], ['deputes.id_an'], ),
    sa.ForeignKeyConstraint(['scrutin_uid'], ['scrutins.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scrutin_uid', 'depute_id', name='uq_scrutin_depute')
    )
    op.create_index(op.f('ix_votes_depute_id'), 'votes', ['depute_id'], unique=False)
    op.create_index(op.f('ix_votes_scrutin_uid'), 'votes', ['scrutin_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_scrutin_uid'), table_name='votes')
    op.drop_index(op.f('ix_votes_depute_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_deputes_groupe_id'), table_name='deputes')
    op.drop_table('deputes')
    op.drop_table('analyses_ia')
    op.drop_table('sources_meta')
    op.drop_index(op.f('ix_scrutins_date_scrutin'), table_name='scrutins')
    op.drop_table('scrutins')
    op.drop_table('groupes')
    op.drop_table('collectes_log')
    # ### end Alembic commands ###
