"""ajout du champ actif sur groupes

Revision ID: b20d637e5949
Revises: fe6a485c60ea
Create Date: 2026-07-21 00:50:35.609010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20d637e5949'
down_revision: Union[str, Sequence[str], None] = 'fe6a485c60ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupes', sa.Column('actif', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupes', 'actif')
    # ### end Alembic commands ###
