"""ajout du champ actif sur deputes

Revision ID: fe6a485c60ea
Revises: 5ad03a6d6c31
Create Date: 2026-07-21 00:36:12.974288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a485c60ea'
down_revision: Union[str, Sequence[str], None] = '5ad03a6d6c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deputes', sa.Column('actif', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deputes', 'actif')
    # ### end Alembic commands ###
